rules:
  property-sort-order:
    - 2
    - order: recess
  no-important: 0
  final-newline: 2
  quotes: 2
  no-css-comments: 2
  no-vendor-prefixes: 0
  no-misspelled-properties: 2
  space-between-parens: 2
  pseudo-element: 2
  mixin-name-format: 2
  class-name-format: 2
